# Generated by Django 5.2.7 on 2025-12-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
