# Generated by Django 5.2.7 on 2025-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_city_user_country_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='demanded_crops',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='location',
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('org', 'Organization'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
    ]
