# Generated by Django 5.2.7 on 2025-10-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrganizationInvitation',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationMembership',
        ),
    ]
