# Generated by Django 5.2.7 on 2025-12-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_buyer_demanded_crops_remove_buyer_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='profile_pic_url',
        ),
    ]
