# Generated by Django 5.2.7 on 2025-12-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_buyer_demanded_crops_remove_buyer_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='crop_images/')),
                ('name', models.CharField(max_length=150)),
                ('variety', models.CharField(blank=True, max_length=150)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='available', max_length=30)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_crops', to='users.farmer')),
            ],
        ),
    ]
