# Generated by Django 5.2.7 on 2025-12-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='image',
            new_name='image_url',
        ),
    ]
