# Generated by Django 5.2.7 on 2025-12-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2borganization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
    ]
