# Generated by Django 5.2.7 on 2025-12-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperative',
            name='img',
        ),
        migrations.AddField(
            model_name='cooperative',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='coop_images/'),
        ),
    ]
